{% set name = "colcon-python-setup-py" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fcd8d6709e6f4c3a273f2c0b5550d73ca987e93ea39b4b4bd765209e27f57928

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - colcon-core >=0.3.10
    - setuptools

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to identify packages with a setup.py
    file by introspecting the arguments to the setup() function call of setuptools.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
