{% set name = "colcon-python-setup-py" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7c944d9d2b688f14c4ef1b1d962dbaabd53dc05e3a04a89da62e2eece6a2ad5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python >=3.6
  run:
    - python >=3.6
    - colcon-core >=0.6.1
    - setuptools

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to identify packages with a setup.py
    file by introspecting the arguments to the setup() function call of setuptools.

extra:
  recipe-maintainers:
    - j-rivero
    - traversaro
    - seanyen
    - wolfv
